=== Kibos/dotaarea/src/main/resources/dota.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:element name="name" type="xsd:string"></xsd:element>
	<xsd:element name="version" type="xsd:float"></xsd:element>
	<xsd:element name="shortName" type="xsd:string"></xsd:element>
	<xsd:element name="desc" type="xsd:string"></xsd:element>
	<xsd:element name="level" type="xsd:integer"></xsd:element>
	<xsd:element name="order" type="xsd:integer"></xsd:element>
	<xsd:element name="area" type="xsd:string"></xsd:element>
	<xsd:element name="distance" type="xsd:string"></xsd:element>
	<xsd:element name="time" type="xsd:string"></xsd:element>
	<xsd:element name="mana" type="xsd:string"></xsd:element>
	<xsd:element name="shortcut" type="xsd:string"></xsd:element>

	<xsd:element name="heroes" type="heroesType"></xsd:element>
	<xsd:element name="hero" type="heroType"></xsd:element>
	<xsd:element name="skills" type="skillsType"></xsd:element>
	<xsd:element name="skill" type="skillType"></xsd:element>
	<xsd:element name="grades" type="gradesType"></xsd:element>
	<xsd:element name="grade" type="gradeType"></xsd:element>

	<xsd:complexType name="heroesType">
		<xsd:sequence>
			<xsd:element ref="name" maxOccurs="1" />
			<xsd:element ref="version" maxOccurs="1" />
			<xsd:element ref="hero" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="heroType">
		<xsd:sequence>
			<xsd:element ref="name" maxOccurs="1" />
			<xsd:element ref="shortName" maxOccurs="1" />
			<xsd:element ref="desc" maxOccurs="1" />
			<xsd:element ref="skills" maxOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="skillsType">
		<xsd:sequence>
			<xsd:element ref="skill" maxOccurs="4" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="skillType">
		<xsd:sequence>
			<xsd:element ref="name" maxOccurs="1" />
			<xsd:element ref="order" maxOccurs="1" />
			<xsd:element ref="shortcut" maxOccurs="1" />
			<xsd:element ref="desc" maxOccurs="1" />
			<xsd:element ref="area" maxOccurs="1" minOccurs="0" />
			<xsd:element ref="distance" maxOccurs="1" minOccurs="0" />
			<xsd:element ref="time" maxOccurs="1" minOccurs="0" />
			<xsd:element ref="mana" maxOccurs="1" minOccurs="0" />
			<xsd:element ref="grades" maxOccurs="1" />
		</xsd:sequence>

	</xsd:complexType>

	<xsd:complexType name="gradesType">
		<xsd:sequence>
			<xsd:element ref="grade" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="gradeType">
		<xsd:sequence>
			<xsd:element ref="level" maxOccurs="1" />
			<xsd:element ref="desc" maxOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>

</xsd:schema>

=== Kibos/dotaarea/src/main/resources/dota6_67.xml
<?xml version="1.0" encoding="utf-8"?>
<heroes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="schema/dota.xsd">
	<name>dota</name>
	<version>6.67</version>

	<hero>
		<name>普罗德摩尔将军</name>
		<shortName>Kunkka</shortName>
		<desc>在近卫的所有盟军中，只有一个人，在许多大陆上都有着不同但又令人生畏的名字。他的追随者们叫他COCO船长，有的人叫他杰克·斯帕罗，还有的人叫他传说中。</desc>

		<attribute>
			<basic>力量</basic>
			<initShot>128</initShot>
			<initAttack>47-57</initAttack>
			<initCooldown>1.7</initCooldown>
			<initDefense>3.6</initDefense>
			<speed>300</speed>
			<intelligence>16</intelligence>
			<agility>22</agility>
			<strength>18</strength>
			<goupIntelligence>1.85</goupIntelligence>
			<goupAgility>1.3</goupAgility>
			<goupStrength>1.5</goupStrength>
		</attribute>

		<skills>
			<skill>
				<name>洪流</name>
				<order>1</order>
				<shortcut>E</shortcut>
				<desc>通过运用他无与伦比的海洋方面的知识，普罗德摩尔将军有能力在指定的区域召唤一阵水流，2秒之后，水流变成一股汹涌的洪流，冲出地面，将范围内的敌方单位抛至空中，造成伤害并在接下来数秒内降低30%的移动速度。</desc>
				<area>255</area>
				<distance>1500</distance>
				<time>12</time>
				<mana>120</mana>
				<grades>
					<grade>
						<level>1</level>
						<desc>120点伤害，1秒减速</desc>
					</grade>
					<grade>
						<level>2</level>
						<desc>180点伤害，2秒减速</desc>
					</grade>
					<grade>
						<level>3</level>
						<desc>240点伤害，3秒减速</desc>
					</grade>
					<grade>
						<level>4</level>
						<desc>300点伤害，4秒减速</desc>
					</grade>
				</grades>
			</skill>
			<skill>
				<name>潮汐使者</name>
				<order>2</order>
				<shortcut>D</shortcut>
				<desc>普罗德摩尔将军传奇般的宝剑潮汐使者，被大海灌入了不可思议的力量，类似于涨潮和退潮，，每过一定的时间，潮汐使者便被动地给予普罗德摩尔将军额外的力量（增加攻击力和380/420/460/500范围的溅射伤害，仅限一次攻击）。</desc>
				<grades>
					<grade>
						<level>1</level>
						<desc>增加攻击力为15点，间隔16秒</desc>
					</grade>
					<grade>
						<level>2</level>
						<desc>增加攻击力为30点，间隔12秒</desc>
					</grade>
					<grade>
						<level>3</level>
						<desc>增加攻击力为45点，间隔8秒</desc>
					</grade>
					<grade>
						<level>4</level>
						<desc>增加攻击力为60点，间隔4秒</desc>
					</grade>
				</grades>
			</skill>
			<skill>
				<name>地图地标</name>
				<order>3</order>
				<shortcut>X</shortcut>
				<desc>为了能使他的军队迅速集合，普罗德摩尔将军为一个英雄在地上标记其当前的位置，数秒之后，被标记的英雄会立刻返回标记位置。</desc>
				<time>30</time>
				<mana>80/90/100/110</mana>
				<grades>
					<grade>
						<level>1</level>
						<desc>1秒之后返回标记地点，500施法距离</desc>
					</grade>
					<grade>
						<level>2</level>
						<desc>2秒之后返回标记地点，650施法距离</desc>
					</grade>
					<grade>
						<level>3</level>
						<desc>3秒之后返回标记地点，800施法距离</desc>
					</grade>
					<grade>
						<level>4</level>
						<desc>4秒之后返回标记地点，950施法距离</desc>
					</grade>
				</grades>
			</skill>
			<skill>
				<name>幽灵船</name>
				<order>4</order>
				<shortcut>T</shortcut>
				<desc>普罗德摩尔将军召唤出神秘的幽灵船CoCo号，横越战场。CoCo号经过友军时，会为友军灌下CoCo船长的朗姆酒，使其在接下来数秒内提升10%的移动速度，减少所受伤害的一半（酒劲消退时会承受累积的那一半伤害）。幽灵船撞毁后，会对425范围内的敌方单位造成伤害和1秒晕眩。</desc>
				<area>1000</area>
				<time>100</time>
				<mana>150/200/250</mana>
				<grades>
					<grade>
						<level>1</level>
						<desc>CoCo船长的朗姆酒持续5秒，300点伤害</desc>
					</grade>
					<grade>
						<level>2</level>
						<desc>CoCo船长的朗姆酒持续6秒，400点伤害</desc>
					</grade>
					<grade>
						<level>3</level>
						<desc>CoCo船长的朗姆酒持续7秒，500点伤害</desc>
					</grade>
				</grades>
			</skill>
		</skills>
	</hero>
</heroes>
